/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d932791746009abbf25285154c5d449a)
interface __BaseEnv_Env {
	PHOTOS: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
