/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c6ee132252c9e19ad5dd836c07aea360)
interface __BaseEnv_Env {
	PHOTOS: R2Bucket;
	DB: D1Database;
	CLERK_AUTHORIZED_PARTIES: "https://app.pawprint.workers.dev";
	CLERK_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLERK_AUTHORIZED_PARTIES" | "CLERK_SECRET_KEY">> {}
}
