/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ApiMediaRouteImport } from './routes/api.media'
import { Route as ApiSyncRouteImport } from './routes/api.sync'
import { Route as ApiUploadsRouteImport } from './routes/api.uploads'
import { Route as PetsPetIdRouteImport } from './routes/pets.$petId'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiMediaSplatRouteImport } from './routes/api.media.$'
import { Route as PetsPetIdIndexRouteImport } from './routes/pets.$petId.index'
import { Route as PetsPetIdCareRouteImport } from './routes/pets.$petId.care'
import { Route as PetsPetIdHealthRouteImport } from './routes/pets.$petId.health'
import { Route as PetsPetIdJournalRouteImport } from './routes/pets.$petId.journal'
import { Route as PetsPetIdWalksRouteImport } from './routes/pets.$petId.walks'
import { Route as PetsPetIdJournalIndexRouteImport } from './routes/pets.$petId.journal.index'
import { Route as PetsPetIdJournalEntryIdRouteImport } from './routes/pets.$petId.journal.$entryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiMediaRoute,
} as any)
const PetsPetIdIndexRoute = PetsPetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetsPetIdRoute,
} as any)
const PetsPetIdCareRoute = PetsPetIdCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => PetsPetIdRoute,
} as any)
const PetsPetIdHealthRoute = PetsPetIdHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => PetsPetIdRoute,
} as any)
const PetsPetIdJournalRoute = PetsPetIdJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => PetsPetIdRoute,
} as any)
const PetsPetIdWalksRoute = PetsPetIdWalksRouteImport.update({
  id: '/walks',
  path: '/walks',
  getParentRoute: () => PetsPetIdRoute,
} as any)
const PetsPetIdJournalIndexRoute = PetsPetIdJournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetsPetIdJournalRoute,
} as any)
const PetsPetIdJournalEntryIdRoute = PetsPetIdJournalEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => PetsPetIdJournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/pets/$petId': typeof PetsPetIdRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/pets/$petId/care': typeof PetsPetIdCareRoute
  '/pets/$petId/health': typeof PetsPetIdHealthRoute
  '/pets/$petId/journal': typeof PetsPetIdJournalRouteWithChildren
  '/pets/$petId/walks': typeof PetsPetIdWalksRoute
  '/pets/$petId/': typeof PetsPetIdIndexRoute
  '/pets/$petId/journal/$entryId': typeof PetsPetIdJournalEntryIdRoute
  '/pets/$petId/journal/': typeof PetsPetIdJournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/pets/$petId/care': typeof PetsPetIdCareRoute
  '/pets/$petId/health': typeof PetsPetIdHealthRoute
  '/pets/$petId/walks': typeof PetsPetIdWalksRoute
  '/pets/$petId': typeof PetsPetIdIndexRoute
  '/pets/$petId/journal/$entryId': typeof PetsPetIdJournalEntryIdRoute
  '/pets/$petId/journal': typeof PetsPetIdJournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/api/sync': typeof ApiSyncRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/pets/$petId': typeof PetsPetIdRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/pets/$petId/care': typeof PetsPetIdCareRoute
  '/pets/$petId/health': typeof PetsPetIdHealthRoute
  '/pets/$petId/journal': typeof PetsPetIdJournalRouteWithChildren
  '/pets/$petId/walks': typeof PetsPetIdWalksRoute
  '/pets/$petId/': typeof PetsPetIdIndexRoute
  '/pets/$petId/journal/$entryId': typeof PetsPetIdJournalEntryIdRoute
  '/pets/$petId/journal/': typeof PetsPetIdJournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/setup'
    | '/api/media'
    | '/api/sync'
    | '/api/uploads'
    | '/pets/$petId'
    | '/sign-in/$'
    | '/api/media/$'
    | '/pets/$petId/care'
    | '/pets/$petId/health'
    | '/pets/$petId/journal'
    | '/pets/$petId/walks'
    | '/pets/$petId/'
    | '/pets/$petId/journal/$entryId'
    | '/pets/$petId/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/setup'
    | '/api/media'
    | '/api/sync'
    | '/api/uploads'
    | '/sign-in/$'
    | '/api/media/$'
    | '/pets/$petId/care'
    | '/pets/$petId/health'
    | '/pets/$petId/walks'
    | '/pets/$petId'
    | '/pets/$petId/journal/$entryId'
    | '/pets/$petId/journal'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/setup'
    | '/api/media'
    | '/api/sync'
    | '/api/uploads'
    | '/pets/$petId'
    | '/sign-in/$'
    | '/api/media/$'
    | '/pets/$petId/care'
    | '/pets/$petId/health'
    | '/pets/$petId/journal'
    | '/pets/$petId/walks'
    | '/pets/$petId/'
    | '/pets/$petId/journal/$entryId'
    | '/pets/$petId/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ApiMediaRoute: typeof ApiMediaRouteWithChildren
  ApiSyncRoute: typeof ApiSyncRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  PetsPetIdRoute: typeof PetsPetIdRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/pets/$petId/': {
      id: '/pets/$petId/'
      path: '/'
      fullPath: '/pets/$petId/'
      preLoaderRoute: typeof PetsPetIdIndexRouteImport
      parentRoute: typeof PetsPetIdRoute
    }
    '/pets/$petId/care': {
      id: '/pets/$petId/care'
      path: '/care'
      fullPath: '/pets/$petId/care'
      preLoaderRoute: typeof PetsPetIdCareRouteImport
      parentRoute: typeof PetsPetIdRoute
    }
    '/pets/$petId/health': {
      id: '/pets/$petId/health'
      path: '/health'
      fullPath: '/pets/$petId/health'
      preLoaderRoute: typeof PetsPetIdHealthRouteImport
      parentRoute: typeof PetsPetIdRoute
    }
    '/pets/$petId/journal': {
      id: '/pets/$petId/journal'
      path: '/journal'
      fullPath: '/pets/$petId/journal'
      preLoaderRoute: typeof PetsPetIdJournalRouteImport
      parentRoute: typeof PetsPetIdRoute
    }
    '/pets/$petId/walks': {
      id: '/pets/$petId/walks'
      path: '/walks'
      fullPath: '/pets/$petId/walks'
      preLoaderRoute: typeof PetsPetIdWalksRouteImport
      parentRoute: typeof PetsPetIdRoute
    }
    '/pets/$petId/journal/': {
      id: '/pets/$petId/journal/'
      path: '/'
      fullPath: '/pets/$petId/journal/'
      preLoaderRoute: typeof PetsPetIdJournalIndexRouteImport
      parentRoute: typeof PetsPetIdJournalRoute
    }
    '/pets/$petId/journal/$entryId': {
      id: '/pets/$petId/journal/$entryId'
      path: '/$entryId'
      fullPath: '/pets/$petId/journal/$entryId'
      preLoaderRoute: typeof PetsPetIdJournalEntryIdRouteImport
      parentRoute: typeof PetsPetIdJournalRoute
    }
  }
}

interface ApiMediaRouteChildren {
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
}

const ApiMediaRouteChildren: ApiMediaRouteChildren = {
  ApiMediaSplatRoute: ApiMediaSplatRoute,
}

const ApiMediaRouteWithChildren = ApiMediaRoute._addFileChildren(
  ApiMediaRouteChildren,
)

interface PetsPetIdJournalRouteChildren {
  PetsPetIdJournalEntryIdRoute: typeof PetsPetIdJournalEntryIdRoute
  PetsPetIdJournalIndexRoute: typeof PetsPetIdJournalIndexRoute
}

const PetsPetIdJournalRouteChildren: PetsPetIdJournalRouteChildren = {
  PetsPetIdJournalEntryIdRoute: PetsPetIdJournalEntryIdRoute,
  PetsPetIdJournalIndexRoute: PetsPetIdJournalIndexRoute,
}

const PetsPetIdJournalRouteWithChildren =
  PetsPetIdJournalRoute._addFileChildren(PetsPetIdJournalRouteChildren)

interface PetsPetIdRouteChildren {
  PetsPetIdCareRoute: typeof PetsPetIdCareRoute
  PetsPetIdHealthRoute: typeof PetsPetIdHealthRoute
  PetsPetIdJournalRoute: typeof PetsPetIdJournalRouteWithChildren
  PetsPetIdWalksRoute: typeof PetsPetIdWalksRoute
  PetsPetIdIndexRoute: typeof PetsPetIdIndexRoute
}

const PetsPetIdRouteChildren: PetsPetIdRouteChildren = {
  PetsPetIdCareRoute: PetsPetIdCareRoute,
  PetsPetIdHealthRoute: PetsPetIdHealthRoute,
  PetsPetIdJournalRoute: PetsPetIdJournalRouteWithChildren,
  PetsPetIdWalksRoute: PetsPetIdWalksRoute,
  PetsPetIdIndexRoute: PetsPetIdIndexRoute,
}

const PetsPetIdRouteWithChildren = PetsPetIdRoute._addFileChildren(
  PetsPetIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ApiMediaRoute: ApiMediaRouteWithChildren,
  ApiSyncRoute: ApiSyncRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  PetsPetIdRoute: PetsPetIdRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
